install.packages("tidyr")
install.packages("plyr")
install.packages("dplyr")
install.packages("data.table")
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("ggrepel")
install.packages("ggimage")
install.packages("ggnewscale")
install.packages("stringr")
install.packages("reshape")
install.packages("fastDummies")
install.packages("ggvenn")
install.packages("corrplot")
install.packages("RColorBrewer")
install.packages("rstatix")
install.packages("car")
install.packages("ResourceSelection")
install.packages("effects")
install.packages("pROC")
install.packages("ggtext")
install.packages("svglite")
install.packages("circlize")
install.packages("scales")
install.packages("metafor")


if (!require("BiocManager", quietly = TRUE)){install.packages("BiocManager")}
BiocManager::install("ggtree")
BiocManager::install("treeio")
BiocManager::install("phylogram")
BiocManager::install("GenomeInfoDb")
BiocManager::install("GenomeInfoDbData")
BiocManager::install("DESeq2")
BiocManager::install("edgeR")
BiocManager::install("BiocParallel")
BiocManager::install("clusterProfiler")
BiocManager::install("fgsea")
BiocManager::install("ComplexHeatmap")
BiocManager::install("vsn")
BiocManager::install("GO.db") 
BiocManager::install("AnnotationDbi")
BiocManager::install("limma")
BiocManager::install("ape")
BiocManager::install("tidytree")

install.packages("devtools")
library(devtools)
install_github("wjawaid/enrichR")





